package tablesB;
// Generated Jun 17, 2015 3:02:42 PM by HRomRub Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Resete generated by hbm2java
 */
@Entity
@Table(name="resete"
    ,catalog="pilotaje"
)
public class Resete  implements java.io.Serializable {


     private int idresete;

    public Resete() {
    }

    public Resete(int idresete) {
       this.idresete = idresete;
    }
   
     @Id 

    
    @Column(name="idresete", unique=true, nullable=false)
    public int getIdresete() {
        return this.idresete;
    }
    
    public void setIdresete(int idresete) {
        this.idresete = idresete;
    }




}


