package tables8;
// Generated Jun 22, 2015 2:37:51 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Resete generated by hbm2java
 */
@Entity
@Table(name="resete"
    ,catalog="pilotaje8"
)
public class Resete  implements java.io.Serializable {


     private String idresete;

    public Resete() {
    }

    public Resete(String idresete) {
       this.idresete = idresete;
    }
   
     @Id 

    
    @Column(name="idresete", unique=true, nullable=false, length=1)
    public String getIdresete() {
        return this.idresete;
    }
    
    public void setIdresete(String idresete) {
        this.idresete = idresete;
    }




}


