package tables8;
// Generated Jun 22, 2015 2:37:51 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name="usuarios"
    ,catalog="pilotaje8"
)
public class Usuarios  implements java.io.Serializable {


     private String expediente;
     private String apaterno;
     private String amaterno;
     private String nombre;
     private String pwd;

    public Usuarios() {
    }

	
    public Usuarios(String expediente) {
        this.expediente = expediente;
    }
    public Usuarios(String expediente, String apaterno, String amaterno, String nombre, String pwd) {
       this.expediente = expediente;
       this.apaterno = apaterno;
       this.amaterno = amaterno;
       this.nombre = nombre;
       this.pwd = pwd;
    }
   
     @Id 

    
    @Column(name="expediente", unique=true, nullable=false, length=5)
    public String getExpediente() {
        return this.expediente;
    }
    
    public void setExpediente(String expediente) {
        this.expediente = expediente;
    }

    
    @Column(name="APaterno", length=25)
    public String getApaterno() {
        return this.apaterno;
    }
    
    public void setApaterno(String apaterno) {
        this.apaterno = apaterno;
    }

    
    @Column(name="Amaterno", length=25)
    public String getAmaterno() {
        return this.amaterno;
    }
    
    public void setAmaterno(String amaterno) {
        this.amaterno = amaterno;
    }

    
    @Column(name="Nombre", length=25)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="pwd", length=10)
    public String getPwd() {
        return this.pwd;
    }
    
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }




}


